site_name: DevOpsTricks
site_url: https://emphie.pl/devops
site_description: Baza wiedzy, która pomoże Ci poznać tajniki DevOps.
docs_dir: ./docs/
theme:
  name: material
  language: pl
  palette:
    primary: black
    accent: indigo
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
  #logo: ./assets/devops-icon.png
  #favicon: ./assets/devops-icon.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
- Zacznij tutaj: index.md
- Linux: linux-cheatsheet.md
- Bash: bash-cheatsheet.md
- Cloud Computing: cloud-computing.md
- AWS:
  - O AWS w skrócie: aws.md
  - Region &amp; Availability Zone: aws/region-az.md
  - ECS - Elastic Container Service: aws/ecs.md
  - SES - Amazon Simple Email Service: aws/ses.md
  - SQS - Amazon Simple Queue Service: aws/sqs.md
- Narzędzia:
  - Iptables: narzedzia/iptables.md
  - Kubernetes: narzedzia/kubernetes.md
  - Klucze prywatne / publiczne: narzedzia/ssh.md
  - SSH: narzedzia/keys.md
  - Terraform: narzedzia/terraform.md
- Linki DevOps: links.md

copyright: 2022 <a href="https://emphie.pl/devops">DevOpsTricks</a> &copy; <a href="https://adrianpietka.com">Adrian Piętka</a>.

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://bit.ly/devenv-slack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adrianpietka/
    - icon: fontawesome/brands/github
      link: https://github.com/adrianpietka/devops-knowledge-base